#mqtt
com:
  mqtt:
    host: tcp://10.200.0.91:1883
    clientid: client11
    topic: demo/topics
    timeout: 10
    keepalive: 20
    maxReconnectTimes: 5
    reconnInterval: 1
    prefixUrl: http://10.200.0.91:18083
    qos: 0

server:
  port: 9090
